essol2/samdadoProject

src/main/java/com/kh/samdado/bussiness/model/vo/tour/TourBooking.java
src/main/java/com/kh/samdado/bussiness/model/vo/tour/TourProduct.java

[Tour 객체만 푸쉬]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java

[충돌 때문에 하는 푸시]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/webapp/WEB-INF/views/mypage/mp_bUserInfo.jsp

[마이페이지 제휴회원 회원정보 수정]

---

src/main/java/com/kh/samdado/bussiness/controller/bussinessController.java
src/main/java/com/kh/samdado/bussiness/model/vo/Jjim.java
src/main/java/com/kh/samdado/bussiness/model/vo/Review.java
src/main/java/com/kh/samdado/bussiness/model/vo/bussiness/Bussiness.java
src/main/java/com/kh/samdado/bussiness/model/vo/bussiness/BussniessAtt.java
src/main/java/com/kh/samdado/bussiness/model/vo/hotel/RoomAtt.java
src/main/java/com/kh/samdado/bussiness/model/vo/rentcar/CarAtt.java
src/main/webapp/WEB-INF/views/bussiness/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/bussiness/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/bussiness/tour/tour_list.jsp
src/main/webapp/WEB-INF/views/common/main.jsp
src/main/webapp/WEB-INF/views/common/navi.jsp

비지니스컨트롤러 수정, 메인 및 다른페이지에서 매핑주소수정, 첨부파일,후기,찜 객체 추가

[비지니스컨트롤러 매핑수정, 객체추가]

---

src/main/webapp/WEB-INF/views/common/main.jsp
src/main/webapp/WEB-INF/views/common/navi.jsp
src/main/webapp/WEB-INF/views/route/route_main.jsp

navi.jsp 수정, route에 gif 제거, 내비에서 삼다도 누르면 홈으로 갈 수 있게 연결

[루트 페이지 gif 빼기 + 알파]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java

[관리자 마이페이지 정보수정 기능수정]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDao.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDaoImpl.java
src/main/java/com/kh/samdado/admin/model/service/AdminServiceImpl.java
src/main/java/com/kh/samdado/mypage/model/vo/QnA.java
src/main/resources/mappers/admin-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/admin/adminHome.jsp

[어드민 메인페이지 QnA LIMIT절 SELECT]

---

src/main/webapp/WEB-INF/views/common/navi.jsp

인클루드하는 네비에 전체 제주 관광지보기 매핑 수정 및 등록

[네비jsp에 관광지 매핑 등록]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDao.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDaoImpl.java
src/main/java/com/kh/samdado/admin/model/service/AdminService.java
src/main/java/com/kh/samdado/admin/model/service/AdminServiceImpl.java
src/main/resources/mappers/admin-mapper.xml
src/main/webapp/WEB-INF/views/admin/adminHome.jsp
src/main/webapp/WEB-INF/views/admin/adminQna.jsp

기능 완료
페이징 처리 및 검색은 이번주 내로 해볼게용...

[어드민 QnA 답변 및 상태 DB 업데이트]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/admin/model/vo/PageInfo.java
src/main/webapp/WEB-INF/views/admin/admin-navi-up.jsp

[어드민 총 누적 회원수 + 신규 QnA 수]

---

src/main/java/com/kh/samdado/route/model/dao/RouteDao.java
src/main/java/com/kh/samdado/route/model/dao/RouteDaoImpl.java
src/main/java/com/kh/samdado/route/model/service/RouteServiceImpl.java

[Route dao, service 추가]

---

src/main/webapp/WEB-INF/views/common/main.jsp
src/main/webapp/WEB-INF/views/common/navi.jsp
src/main/webapp/WEB-INF/views/route/modal.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp
src/main/webapp/resources/css/common/navi.css
src/main/webapp/resources/css/route/route_modal.css
src/main/webapp/resources/css/user/addMember.css

[route_result 모달 css 고치기]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDao.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDaoImpl.java
src/main/java/com/kh/samdado/admin/model/service/AdminService.java
src/main/java/com/kh/samdado/admin/model/service/AdminServiceImpl.java
src/main/java/com/kh/samdado/admin/model/vo/Pagination.java
src/main/webapp/WEB-INF/views/admin/adminQna.jsp

[어드민 신규 qna 페이징처리]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/webapp/WEB-INF/views/common/navi.jsp
src/main/webapp/WEB-INF/views/route/modal.jsp
src/main/webapp/WEB-INF/views/route/route_main.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp
src/main/webapp/resources/css/route/route_modal.css

[route_result 페이지 이것저것 수정]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_Point.jsp

[마이페이지 포인트 기능 완성]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp
src/main/webapp/WEB-INF/views/common/main.jsp
src/main/webapp/WEB-INF/views/common/navi.jsp

디테일페이지 자바스크립트 보충, 네비/메인 매핑 수정, 등록값땡겨오기

[0402 학원등원 노트북작업]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/java/com/kh/samdado/mypage/model/vo/SearchPoint.java
src/main/webapp/WEB-INF/views/mypage/mp_Point.jsp

[포인트 검색 기능 front 만듬!]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/java/com/kh/samdado/route/model/vo/Search.java
src/main/webapp/WEB-INF/views/route/route_main.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp

route_main -> route_result 검색 조건 연결 + 쫌쫌따리

[route 검색 조건 연결]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDao.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDaoImpl.java
src/main/java/com/kh/samdado/admin/model/service/AdminService.java
src/main/java/com/kh/samdado/admin/model/service/AdminServiceImpl.java
src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/java/com/kh/samdado/common/model/vo/Report.java
src/main/resources/mappers/admin-mapper.xml
src/main/resources/mappers/business-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/admin/admin-navi-up.jsp

[어드민 REPORT]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDao.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDaoImpl.java
src/main/java/com/kh/samdado/admin/model/service/AdminService.java
src/main/java/com/kh/samdado/admin/model/service/AdminServiceImpl.java
src/main/java/com/kh/samdado/user/controller/UserController.java
src/main/resources/mappers/admin-mapper.xml
src/main/webapp/WEB-INF/views/admin/adminReportManage.jsp
src/main/webapp/WEB-INF/views/admin/adminuserList.jsp
src/main/webapp/WEB-INF/views/common/navi.jsp
src/main/webapp/resources/css/common/navi.css

[어드민 신고 update]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/java/com/kh/samdado/mypage/model/vo/AccountBook.java
src/main/resources/mappers/mypage_mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/mypage/mp_Point.jsp
src/main/webapp/WEB-INF/views/mypage/mp_UserInfo.jsp
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

mybatis-config에 AccountBook 추가!

[마이페이지-가게부 insert, 첫 화면 select]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/java/com/kh/samdado/route/model/dao/RouteDao.java
src/main/java/com/kh/samdado/route/model/dao/RouteDaoImpl.java
src/main/java/com/kh/samdado/route/model/service/RouteService.java
src/main/java/com/kh/samdado/route/model/service/RouteServiceImpl.java
src/main/java/com/kh/samdado/route/model/vo/rSearch.java
src/main/resources/mybatis-config.xml

[route Search 이름 변경]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/java/com/kh/samdado/mypage/model/vo/AccountBook.java
src/main/webapp/WEB-INF/views/mypage/mp_Point.jsp
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

마이페이지 포인트 출력 수정
가계부 insert modal form 수정

[마이페이지 포인트 수정,가게부 css 수정]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/vo/AccountBook.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

[마이페이지 가계부 리스트 출력]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

[마이페이지 가계부 - 엑셀로 export]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp

[신고하기 db insert 끝]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/java/com/kh/samdado/mypage/model/vo/AccountBook.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

총액 계산, 테이블 출력 요소 수정, 날짜별 조회 기능 구현

[마이페이지 가계부]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/webapp/WEB-INF/views/route/route_edit.jsp
src/main/webapp/WEB-INF/views/route/route_main.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp
src/main/webapp/resources/css/route/route_main.css
src/main/webapp/resources/css/route/route_result.css

[route route 수정사항]

---

src/main/resources/mappers/business-mapper.xml

[비즈니스 매퍼 수정]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_MyReservation.jsp
src/main/webapp/WEB-INF/views/mypage/mp_UserInfo.jsp
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

가계부도 좀 바꾸긴 했는데 된건 없음
마이페이지 예약페이지 이동 연결해놓음

[마이페이지 예약목록 이동]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

[마이페이지 가계부, 포인트]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/webapp/WEB-INF/views/mypage/mp_Point.jsp

인서트 후 잔여 포인트+ 내역 출력 안되는거 해결 완료!

[마이페이지 포인트 수정]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/java/com/kh/samdado/mypage/model/vo/AccountBook.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

[마이페이지 가계부 기능]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp

데이트피커(달력) + 리터럴하게 값 박고 결제api띄우기

[0408 결제api + 데이트피커작업]

---

src/main/resources/mappers/business-mapper.xml

이제 진짜 되는것 같은데 안되는것 같기도 하고.. 잘 모르겠다 ㅎ.;

[포인트 차감 쿼리문 수정]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

[마이페이지 가계부 기능 끝]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp
src/main/webapp/WEB-INF/views/common/navi.jsp

[0412 야간작업 detail페이지]

---

src/main/java/com/kh/samdado/business/model/vo/business/Business.java
src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/common/navi.jsp
src/main/webapp/WEB-INF/views/mypage/mp_Point.jsp
src/main/webapp/WEB-INF/views/mypage/mp_QnA.jsp
src/main/webapp/WEB-INF/views/mypage/mp_StoreList.jsp
src/main/webapp/WEB-INF/views/mypage/mp_bUserInfo.jsp

리스트 출력 + 상세페이지로 연결 + 새로운 사업장 추가 까지!

[마이페이지 내 사업장]

---

src/main/resources/mappers/admin-mapper.xml
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/common/main-section.jsp

[매퍼 쿼리문 수정]

---

src/main/webapp/WEB-INF/views/route/route_result.jsp

[route polyline]

---

src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp

각 리스트페이지마다 랜덤출력 + 리스트 9개 이상이면 더보기작동. 프리미엄제외

[더보기 + 리스트랜덤출력 끝]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/common/model/vo/Alliance.java
src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/java/com/kh/samdado/mypage/model/vo/ApplyPageInfo.java
src/main/java/com/kh/samdado/mypage/model/vo/ApplyPagination.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_Advertisement.jsp
src/main/webapp/WEB-INF/views/mypage/mp_Point.jsp
src/main/webapp/WEB-INF/views/mypage/mp_QnA.jsp
src/main/webapp/WEB-INF/views/mypage/mp_StoreList.jsp
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp
src/main/webapp/WEB-INF/views/mypage/mp_bUserInfo.jsp

차트, 클릭수 빼고 리스트 출력 + 페이징 처리 완료!

[마이페이지 광고관리 리스트 출력]

---

src/main/webapp/WEB-INF/views/mypage/mp_Advertisement.jsp

[데모 브랜치 확인용 브랜치 푸시]

---

src/main/webapp/WEB-INF/views/mypage/mp_Advertisement.jsp

[데모 확인용 브랜치2]

---

src/main/webapp/WEB-INF/views/mypage/mp_Advertisement.jsp

[21.04.14]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/resources/mappers/business-mapper.xml
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp

[마이페이지 컨트롤러/매퍼 수정 + 카리스트 더보기 수정]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/java/com/kh/samdado/route/model/dao/RouteDao.java
src/main/java/com/kh/samdado/route/model/dao/RouteDaoImpl.java
src/main/java/com/kh/samdado/route/model/service/RouteService.java
src/main/java/com/kh/samdado/route/model/service/RouteServiceImpl.java
src/main/resources/mappers/route-mapper.xml
src/main/webapp/WEB-INF/views/route/route_result.jsp
src/main/webapp/resources/css/route/route_modal.css

[route modal 검색]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp

[0416 필터링스크립트+수수료결제]

---

src/main/java/com/kh/samdado/business/model/vo/business/Business.java
src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_Advertisement.jsp

클릭수 계산해서 출력하기
차트 데이터 불러오기(중도포기)

[마이페이지 광고관리]

---

src/main/java/com/kh/samdado/business/model/vo/business/Business.java
src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_Advertisement.jsp
src/main/webapp/WEB-INF/views/mypage/mp_MyReservation.jsp
src/main/webapp/WEB-INF/views/mypage/mp_UserInfo.jsp
src/main/webapp/WEB-INF/views/mypage/mp_Wallet.jsp

[마이페이지 광고관리 완성]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp

몇가지 값만 리터럴하게만 되고 나머지 정상. 수정 더 필요

[투어 결제 스크립트보강]

---

src/main/webapp/WEB-INF/views/route/route_edit.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp

[route_edit 순서 바꾸기]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp

[신고하기 insert 진짜 끝]

---

src/main/resources/mappers/business-mapper.xml

[신고 쿼리문 리터럴값 수정]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDao.java
src/main/java/com/kh/samdado/admin/model/dao/AdminDaoImpl.java
src/main/java/com/kh/samdado/admin/model/service/AdminService.java
src/main/java/com/kh/samdado/admin/model/service/AdminServiceImpl.java
src/main/java/com/kh/samdado/user/model/vo/EmailSender.java
src/main/resources/mappers/admin-mapper.xml
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp

[신고 3회 승인 rexdate | rcount update]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp

[0420 임시푸쉬]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/java/com/kh/samdado/mypage/model/vo/Alert.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/admin/adminReportManage.jsp

중간에 풀 땡기기 위해서 push 하는데 타겟이랑 이상한 얘들도 같이 올라옴; 왜이래 또...

[마이페이지 알람 report 넣기]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/java/com/kh/samdado/user/model/vo/User.java
src/main/resources/mappers/admin-mapper.xml
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/admin/adminAd1Manage.jsp
src/main/webapp/WEB-INF/views/admin/adminReportManage.jsp
src/main/webapp/WEB-INF/views/common/main-section.jsp

[어드민 신고 | 배너광고 서치 ajax 모달 띄우기]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/java/com/kh/samdado/mypage/model/vo/Alert.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_news.jsp

[마이페이지 내소식 포인트 빼고 다함!]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/resources/mappers/mypage_mapper.xml

[은솔 - 등록하고 마이페이지로 가는 프로세스 수정]

---

src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp

[호텔예약 완벽히끝]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp

[신고하기 손보기]

---

src/main/java/com/kh/samdado/user/model/vo/User.java
src/main/resources/mappers/user-mapper.xml
src/main/webapp/WEB-INF/views/admin/adminHome.jsp
src/main/webapp/WEB-INF/views/admin/adminuserList.jsp
target/classes/mappers/user-mapper.xml

[admin 유저리스트 출력 pbalance 컬럼 추가 및 회원정보 리스트에서 전화번호 클릭 시 모달창으로 sms 내용입력창 뜨게

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/java/com/kh/samdado/business/model/vo/Jjim.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp

[레스토랑디테일페이지 찜기능 구현완료]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp

[찜셀렉에 리터럴하게 들어갔던 값 수정]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/java/com/kh/samdado/route/model/dao/RouteDao.java
src/main/java/com/kh/samdado/route/model/dao/RouteDaoImpl.java
src/main/java/com/kh/samdado/route/model/service/RouteService.java
src/main/java/com/kh/samdado/route/model/service/RouteServiceImpl.java
src/main/resources/mappers/route-mapper.xml
src/main/webapp/WEB-INF/views/route/route_edit.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp

[route 저장]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/vo/business/Business.java
src/main/resources/mappers/business-mapper.xml

[0423 데모 풀땡길라고 임시 푸쉬]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/mypage/model/vo/Booking.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp

리터럴값 -> 값 가져오기 수정. 카 다른사진만 리터럴

[카 부킹 예약 끝]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp

[모든 디테일 페이지 찜적용 + 카디테일 수정]

---

src/main/java/com/kh/samdado/mypage/controller/MypageController.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDao.java
src/main/java/com/kh/samdado/mypage/model/dao/MypageDaoImpl.java
src/main/java/com/kh/samdado/mypage/model/service/MypageService.java
src/main/java/com/kh/samdado/mypage/model/service/MypageServiceImpl.java
src/main/resources/mappers/mypage_mapper.xml
src/main/webapp/WEB-INF/views/mypage/mp_UserInfo.jsp
src/main/webapp/WEB-INF/views/mypage/mp_bUserInfo.jsp

[마이페이지 지도 이외의 기능 완성]

---

src/main/webapp/WEB-INF/views/route/route_edit.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp

[route result, edit]

---

src/main/java/com/kh/samdado/business/model/vo/business/Business.java
src/main/resources/mappers/business-mapper.xml

리스트 가져올때 rexdate가 null이 아닌걸 제외하고 가져옴

[누적신고3회시 리스트에서 출력X]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/resources/mappers/business-mapper.xml

rexdate 가져와서 sysdate와 비교 -> 기간 지났으면 null로 업데이트

[신고 제재기간 끝나면 다시 리스트에 출력]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/java/com/kh/samdado/route/model/dao/RouteDao.java
src/main/java/com/kh/samdado/route/model/dao/RouteDaoImpl.java
src/main/java/com/kh/samdado/route/model/service/RouteService.java
src/main/java/com/kh/samdado/route/model/service/RouteServiceImpl.java
src/main/resources/mappers/route-mapper.xml
src/main/webapp/WEB-INF/views/route/route_edit.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp

[route 검색-추가]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/resources/mappers/business-mapper.xml

income테이블의 exdate도 null로 update

[프리미엄 만료되면 일반으로 강등]

---

src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp

[리터럴값 -> db데이터 끌어오기]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/hotel/hotel_write.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/rentcar_write.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_write.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_write.jsp

[사업장 디테일 수정]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/user/controller/UserController.java
src/main/webapp/WEB-INF/views/admin/adminAd1Manage.jsp
src/main/webapp/WEB-INF/views/admin/adminAd2Manage.jsp
src/main/webapp/WEB-INF/views/admin/adminQna.jsp
src/main/webapp/WEB-INF/views/admin/adminReportManage.jsp
src/main/webapp/WEB-INF/views/admin/adminuserList.jsp
src/main/webapp/WEB-INF/views/common/main.jsp

날짜 search안되는거 수정 - 검색 못하게 주석처리, 회원 탈퇴시 로그인 안되게 수정, 회원가입시 바로 로그인 안되는거 수정

[자잘한 에러 수정]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp

[신고 alert 제대로 뜨기]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp

[예약하기 스크립트 에러 수정]

---

src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp

[렌트카 예약하기 수정]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp

[투어예약 css수정]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp

[호텔 예약 css수정]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/resources/mappers/route-mapper.xml
src/main/webapp/WEB-INF/views/route/route_edit.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp

[route 사업장]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/vo/Review.java
src/main/java/com/kh/samdado/business/model/vo/business/Business.java
src/main/webapp/WEB-INF/views/business/hotel/hotel_write.jsp

[사업장 호텔등록 수정]

---

src/main/java/com/kh/samdado/business/controller/businessController.java

[사업장리스트연결]

---

src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/java/com/kh/samdado/route/model/dao/RouteDao.java
src/main/java/com/kh/samdado/route/model/dao/RouteDaoImpl.java
src/main/java/com/kh/samdado/route/model/service/RouteService.java
src/main/java/com/kh/samdado/route/model/service/RouteServiceImpl.java
src/main/resources/mappers/route-mapper.xml
src/main/webapp/WEB-INF/views/route/route_edit.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp

[route 찜한 사업장]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp
src/main/webapp/resources/css/common/footer.css
src/main/webapp/resources/css/user/addMember.css

리스트,디테일페이지,푸터css 애드멤버css수정. 리스트찜하기사진수정완료

[페이지들 제주명조폰트 제거]

---

src/main/java/com/kh/samdado/admin/controller/AdminController.java
src/main/java/com/kh/samdado/user/controller/UserController.java
src/main/webapp/WEB-INF/views/business/businessFormSubmit.jsp
src/main/webapp/WEB-INF/views/common/aboutUs.jsp
src/main/webapp/WEB-INF/views/common/main.jsp

[비즈니스 폼 서브밋 css 수정]
[메인 navi border z-index 수정]

[어바웃어스 오타 수정]

---

src/main/webapp/WEB-INF/views/common/footer.jsp
src/main/webapp/WEB-INF/views/common/navi.jsp
src/main/webapp/resources/css/common/footer.css

z-index 수정
근대 캐시가 안지워져서 footer.css 파일 뒤에 ?v=3 으로 캐싱처리 해줬는데도 안먹어서... 모징?

[include navi]

---

src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/java/com/kh/samdado/route/controller/RouteController.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp

길찾기 프리미엄으로 랜덤2개 가져오기, 넘버포맷 일부분만

[길찾기 추천숙박 띄우기, 넘버포맷]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/hotel/hotel_write.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/rentcar_write.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_write.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_write.jsp

등록페이지 컴마추가정규식 제거, 나머지 페이지에 fmt 넘버포맷

[디테일,리스트,라이트 페이지 수정]

---

src/main/webapp/WEB-INF/views/route/route_edit.jsp
src/main/webapp/WEB-INF/views/route/route_result.jsp
src/main/webapp/resources/css/route/route_result.css

[map margin]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp

[사업장 몇가지 디테일]'

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp

[호텔예약 렌트카예약 리스트페이지필터링css수정]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp

[차 다른사진 제거, 유저테이블에 pbalance 업데이트]

---

src/main/java/com/kh/samdado/business/controller/businessController.java
src/main/java/com/kh/samdado/business/model/dao/businessDao.java
src/main/java/com/kh/samdado/business/model/dao/businessDaoImpl.java
src/main/java/com/kh/samdado/business/model/service/businessService.java
src/main/java/com/kh/samdado/business/model/service/businessServiceImpl.java
src/main/java/com/kh/samdado/business/model/vo/business/Business.java
src/main/resources/mappers/business-mapper.xml
src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp

[리스트페이지 카테고리]

---

src/main/webapp/WEB-INF/views/common/naviWhite.jsp

[네비화이트 메뉴수정]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp

[리스트에서 찜버튼 치움]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_detail.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_detail.jsp

[호텔 리뷰css수정]

---

src/main/webapp/WEB-INF/views/business/rentcar/car_detail.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp

[카디테일 리뷰css 수정]

---

src/main/webapp/WEB-INF/views/business/hotel/hotel_list.jsp
src/main/webapp/WEB-INF/views/business/rentcar/car_list.jsp
src/main/webapp/WEB-INF/views/business/restaurant/restaurant_list.jsp
src/main/webapp/WEB-INF/views/business/tour/tour_list.jsp

[검색 후 밸류 초기화]
